# Generated by Django 3.0 on 2020-12-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_box_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_message',
            name='chat_box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat_box'),
            preserve_default=False,
        ),
    ]
