# Generated by Django 3.0 on 2020-12-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chat_message_chat_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_message',
            name='chat_box',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat_box'),
            preserve_default=False,
        ),
    ]
