# Generated by Django 3.0 on 2020-12-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_chat_message_chat_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_message',
            name='chat_box',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
