# Generated by Django 3.0 on 2020-12-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20201227_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_message',
            name='chat_box',
            field=models.TextField(),
        ),
    ]
